baseURL: 'https://www.diginas.fr/'
languageCode: en-us
DefaultContentLanguage: en
title: Digital innovations As services
theme: diginas
languages:
  en:
    languageName: English
    weight: 1
    contentDir: content/en
  fr:
    languageName: Français
    weight: 2
    contentDir: content/fr
    menu:
      nav:
        - name: Qui Sommes-nous
          URL: about
          weight: 2
        - name: Nos Services
          URL: services
          weight: 3
        #- name: Nos Compétences
        #  URL: team-skills
        #  weight: 5
        - name: Join us
          URL: join
          weight: 6
        #- name: Blog#
        #  URL: blog
        #  weight: 7
        - name: Contact
          URL: contact-us
          weight: 8
    params:
#Home
      home: Accueil
#Banner
      banner:
        enable: true
        bgImage: images/slider/hero-area.jpg
        icon: tf-ion-play
        heading: Digital Innovations As Services
        content: >-
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugit, excepturi.
          At recusandae sit perferendis autem,iste tempora nostrum numquam sapiente!
        btnText: Exploranos
        btnURL: '#services'
      cta:
        title: Un design exceptionnel et des fonctionnalités incroyables
        content: >-
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Officiis tenetur
          odio impedit incidunt? Omnis accusantium ea reiciendis, fugit commodi
          nostrum.
        btnText: Commencer un projet avec nous
#  es:
#    languageName: Spanish
#    contentDir: content/es
#    weight: 3
#    menu:
#      nav:
#        - name: sobre nosotros
#          URL: about
#          weight: 2
#        - name: Nuestros servicios
#          URL: services
#          weight: 3
#        - name: habilidades
#          URL: team-skills
#          weight: 5
#        - name: Join us
#          URL: join
#          weight: 6
#        - name: Blog
#          URL: blog
#          weight: 7
#        - name: Contacto
#          URL: contact-us
#          weight: 8
#    params:
#      home: inicio
#      banner:
#        enable: true
#        bgImage: images/slider/hero-area.jpg
#        icon: tf-ion-play
#        heading: Digital Innovations As Services
#        content: >-
#          Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugit, excepturi.
#          At recusandae sit perferendis autem,iste tempora nostrum numquam sapiente!
#        btnText: Exploranos
#      cta:
#        title: Gran diseño y características increíbles
#        content: >-
#          Lorem ipsum dolor sit amet consectetur adipisicing elit. Officiis tenetur
#          odio impedit incidunt? Omnis accusantium ea reiciendis, fugit commodi
#          nostrum.
#        btnText: Comienza un proyecto con nosotros.
menu:
  nav:
    - name: About Us
      URL: about
      weight: 2
    - name: Services
      URL: services
      weight: 3
    # name: Skills
    #  URL: team-skills
    #  weight: 5
    - name: Join us
      URL: join
      weight: 6
    - name: Blog
      URL: blog
      weight: 7
    - name: Contact
      URL: contact-us
      weight: 8
params:
  home: Home
  logo: images/logo.png
  description: Your Digital partner for innovation & transformation
  author: Diginas
  googleAnalitycsID: Your ID
  custom_css:
    - css/custom.css
  banner:
    enable: true
    bgImage: images/slider/hero-area.jpg
    icon: tf-ion-play
    heading: Digital Innovations As Services
    content: >-
      Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugit, excepturi.
      At recusandae sit perferendis autem,iste tempora nostrum numquam sapiente!
    btn: true
    btnText: Explore Us
    btnURL: '#services'
  cta:
    enable: true
    title: Great Design & Incredible Features
    content: >-
      Lorem ipsum dolor sit amet consectetur adipisicing elit. Officiis tenetur
      odio impedit incidunt? Omnis accusantium ea reiciendis, fugit commodi
      nostrum.
    btnURL: '#'
    btnText: Start a project with us
  counter:
    enable: false
    bgImage: images/backgrounds/bg-1.jpg
    counterItem:
      - title: Happy Clients
        icon: tf-ion-android-happy
        count: '320'
      - title: Projects completed
        icon: tf-ion-archive
        count: '565'
      - title: Positive feedback
        icon: tf-ion-thumbsup
        count: '95'
      - title: Cups of Coffee
        icon: tf-ion-coffee
        count: '2500'
  footer:
    copyright: Diginas
    copyrightURL: 'http://www.diginas.fr'
    socialIcon:
      - icon: tf-ion-social-twitter
        url: '#'
      - icon: tf-ion-social-linkedin
        url: '#'
