name = "Diginas"
license = ""
licenselink = "https://creativecommons.org/licenses/by/3.0/"
description = ""
homepage = "Diginas"
tags = ['landing-page', 'google-analytics', 'transformation', 'digital', 'DevOps', 'minimalistic', 'business', 'agency-template', 'Agility', 'analytics', 'management', 'bootstrap', 'blog', 'responsive', 'portfolio', 'single-page', 'innovations', 'clean', 'simple', 'company', 'creative', 'challenge', 'UX based Development', 'mobile']
features = ['bootstrap','responsive']
min_version = "0.48"

[author]
  name = "Diginas"
  homepage = "https://www.diginas.fr"
